import 'package:flutter/material.dart';
import '../models/task.dart';

class TaskItem extends StatelessWidget {
  final Task task; final VoidCallback onComplete, onDelete, onTap;
  const TaskItem({super.key, required this.task, required this.onComplete, required this.onDelete, required this.onTap});
  String time() => task.dueDate == null ? 'No due time' : '${task.dueDate!.hour.toString().padLeft(2,'0')}:${task.dueDate!.minute.toString().padLeft(2,'0')}';
  @override Widget build(BuildContext context) { final c=Theme.of(context).colorScheme; return Dismissible(key:ValueKey(task.id), background:Container(margin:const EdgeInsets.only(bottom:10),alignment:Alignment.centerLeft,padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.green.withOpacity(.16),borderRadius:BorderRadius.circular(24)),child:const Icon(Icons.done_rounded)), secondaryBackground:Container(margin:const EdgeInsets.only(bottom:10),alignment:Alignment.centerRight,padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.red.withOpacity(.14),borderRadius:BorderRadius.circular(24)),child:const Icon(Icons.delete_outline)), confirmDismiss:(d) async {if(d==DismissDirection.startToEnd){onComplete();return false;} onDelete();return true;}, child: GestureDetector(onTap:onTap, child: Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:LinearGradient(colors:[c.surface.withOpacity(.82),c.surfaceContainerHighest.withOpacity(.38)]),border:Border.all(color:c.outline.withOpacity(.08))),child:Row(children:[GestureDetector(onTap:onComplete,child:AnimatedContainer(duration:const Duration(milliseconds:250),width:30,height:30,decoration:BoxDecoration(shape:BoxShape.circle,color:task.completed?c.primary:Colors.transparent,border:Border.all(color:task.completed?c.primary:c.onSurfaceVariant,width:2)),child:task.completed?Icon(Icons.check,size:18,color:c.onPrimary):null)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(task.title,style:TextStyle(fontSize:16,fontWeight:FontWeight.w650,decoration:task.completed?TextDecoration.lineThrough:null,color:task.completed?c.onSurfaceVariant:null)),const SizedBox(height:7),Row(children:[Text('●',style:TextStyle(fontSize:12,color:task.priority==TaskPriority.high?c.primary:task.priority==TaskPriority.medium?c.secondary:c.outline)),const SizedBox(width:6),Text(time(),style:TextStyle(fontSize:12,color:c.onSurfaceVariant)),const SizedBox(width:10),Text(task.category.name,style:TextStyle(fontSize:12,color:c.onSurfaceVariant))])]))] ))));}
}
